
name: Release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}
jobs:
  release:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: release
        run: |
          set -euxo pipefail
          version=$(jq -r .version  Assets/FishNet/package.json)
          bash ./deploy.sh --semver $version
          
# https://github.com/WolffunGame/FishNet.git#3.5.6